-- find total customers by country
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- find total products by category
SELECT
category,
--- subcategory,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category --, subcategory
ORDER BY /*category,*/ total_products DESC

-- what is average cost in each category
SELECT
category,
--- subcategory,
AVG(cost) AS AVG_costs
FROM gold.dim_products
GROUP BY category --, subcategory
ORDER BY /*category,*/ AVG_costs DESC

-- what is the total revenue generated for each category
SELECT
p.category,
SUM(f.sales_amount) AS total_Revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_Revenue DESC

-- what total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_Revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_Revenue DESC

-- Note: Jordan Turner appears twice (customer_key 421 & 2421)
-- causing deflated revenue when grouping by customer_key
-- Grouping by first_name/last_name reveals true total: 15,998

-- what is the distribution of sold items across countries
SELECT
c.country,
SUM(f.quantity) AS Sold_Items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY Sold_Items DESC
